language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-19.0.0
  - android-19
sudo: false
cache:
    directories:
        - node_modules
        - src/lib
env:
  global:
  
before_install:

- echo "Before install stage"
install:
- echo "Install stage"
- sed -i -e "s/\$VERSIONCODE/$TRAVIS_BUILD_NUMBER/g" config.xml
- sed -i -e "s/\$VERSIONCODE/$TRAVIS_BUILD_NUMBER/g" package.json
- npm install
- export PATH=$(npm bin):$PATH
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- gulp
- ionic platform add android
- sed -i -e 's/CordovaApp/CarCloud/g' platforms/android/AndroidManifest.xml
- mv platforms/android/src/ie/ianduffy/carcloud/CordovaApp.java platforms/android/src/ie/ianduffy/carcloud/CarCloud.java
- sed -i -e 's/CordovaApp/CarCloud/g' platforms/android/src/ie/ianduffy/carcloud/CarCloud.java
- cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git
- cordova plugin add org.apache.cordova.splashscreen
- cordova plugin add org.apache.cordova.device
- cordova plugin add org.apache.cordova.dialogs
- cordova plugin add org.apache.cordova.network-information
- cordova plugin add https://github.com/driftyco/ionic-plugins-keyboard.git
- mkdir -p platforms/ios/CarCloud/Resources/icons
- mkdir -p platforms/ios/CarCloud/Resources/splash
- cordova-gen www/img/all.png "#FFF"
- ionic build android
after_success:
- bash ./.push-release.sh
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
deploy:
  provider: releases
  api_key:
    secure: 31d238e54dc1d8e9f9c2edc228f5e36de983bc4b
  file: platforms/android/ant-build/CarClouds.apk
  on:
    tags: true
    all_branches: true
