language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-19.0.0
  - android-19
env:
  global:
    secure: O6Jl4M2X0K0IKQ8zq/Em1o5POOI4Xl4DG3qTY/QS1/E4jX0+01UpnX0MhEGWoJwqPspIjbcRaNDQCkrQ7oIt+r/hI5zM0bzXJpZ2wEnatZWb//mDoSU5Ge6kbpVk7PrJNsyuU1lkm55m1122Sj1DKuw2N8ZZxsboWiSdY1zoIdQ=
before_install:
- echo "Before install stage"
install:
- echo "Install stage"
- sudo apt-get install -y python-software-properties
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo apt-get update -y
- sudo apt-get install -y nodejs imagemagick
- sudo npm -g install cordova ionic bower gulp cordova-gen
- sudo npm install
- mkdir {platforms,plugins}
- mkdir -p platforms/ios/CarCloud/Resources/icons
- mkdir -p platforms/ios/CarCloud/Resources/splash
- ionic platform add android
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- cordova-gen www/img/all.png "#FFF"
- ionic build android
after_success:
- git config user.name "Travis-CI"
- git config user.email "travisci@ianduffy.ie"
- git remote set-url origin https://${GH_TOKEN}@github.com/imduffy15/carcloud-mobile-app.git
- git fetch --tags
- git tag $TRAVIS_BUILD_NUMBER
- git push --tags
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
deploy:
  provider: releases
  api_key:
    secure: O6zuQzSv6husuKQkm3XOF2w8wMtxf6osgsN2xisZoGXJoSdk3n5abM17XI23MTzl57CsNnNnk0aASp2gkCUkMvyrXwmVY1aph61ehr6OunNvAnmXsMUF02nglKhmIzMAq7FMOtR/3f4sd1cCeROTEDpZYovFPNnsFIKgrFU4wwM=
  file: platforms/android/out/CarCloud-debug-unaligned.apk
  on:
    tags: true
    all_branches: true