language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-19.0.0
  - android-19
install:
- which android
- find "/usr/local/android-sdk/" "zipalign"
- ls -lah /usr/local/android-sdk/
- ls -lah /usr/bin
- ls -lah /usr/local/bin
